sudo: required

env:
  - dockerTag=pg2k4j

services:
  - docker

language: java

install: /bin/true

script:
  - mvn clean test
  - if [ "$TRAVIS_BRANCH" = "travisPipeline" ]; then echo "on travisPipeline"; fi
