sudo: required

env:
  - dockerTag=pg2k4j

services:
  - docker

language: java

install: true

stages:
  - name: test


jobs:
  include:
    - stage: test
      script: mvn clean test
      name: "Unit Tests"
    - stage: integration_tests
      script: mvn verify
      name: "Integration Tests"
