sudo: required

env:
  - dockerTag=pg2k4j

services:
  - docker

language: java

script:
  - COVERALLS_TOKEN=$COVERALLS_TOKEN mvn clean install jacoco:report
  - bash <(curl -s https://codecov.io/bash)