sudo: required

env:
  - dockerTag=pg2k4j

services:
  - docker

language: java

install: true

script:
  - mvn clean install jacoco:report
  - bash <(curl -s https://codecov.io/bash)
  - nextVersion="$(cat .version | perl -pe 'chomp' | awk -F. "{\$NF = \$NF + 1;} 1" | sed 's/ /./g')"
  - echo $nextVersion
